import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


interface RootLayoutProps {
  children: React.ReactNode
  params: {
    locale: string;
  };
}


export default function RootLayout({ children, params: { locale } }: RootLayoutProps) {

  const messages = useMessages();

  console.log("message",messages)
  return (
  
    <html lang={locale}>
    <body>
      <NextIntlClientProvider locale={locale} messages={messages}>
        {children}
      </NextIntlClientProvider>
    </body>
  </html>
   
  )
}